name: Airtable Sync

on:
  workflow_dispatch:

jobs:
  airtable-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Mostrar Base ID
        run: |
          echo "Base ID: appVZGkndj6o8CyV0"

      - name: Verificar Token
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
        run: |
          if [ -z "$AIRTABLE_TOKEN" ]; then
            echo "Token no encontrado"
            exit 1
          else
            echo "Token encontrado correctamente"
          fi

      - name: Consultar Airtable
        env:
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
        run: |
          curl -X GET \
          "https://api.airtable.com/v0/appVZGkndj6o8CyV0/Proveedores" \
          -H "Authorization: Bearer $AIRTABLE_TOKEN"
